---
# tasks file for GeoIPUpdate
- name: 创建下载目录
  file: path=/opt/software state=directory
- name: 拷贝geoipupdate到远程主机
  synchronize: src={{PkgName}}-{{version}} dest={{Downloads}} recursive=yes delete=yes
- name: 配置geoipupdate
  shell: chdir={{Downloads}}/{{PkgName}}-{{version}} ./configure
- name: 编译geoipupdate
  shell: chdir={{Downloads}}/{{PkgName}}-{{version}} make -j 4
- name: 安装geoipupdate
  shell: chdir={{Downloads}}/{{PkgName}}-{{version}} make install
- name: 同步配置文件
  template: src={{ConfigFile}}.j2 dest=/usr/local/etc/{{ConfigFile}} mode=644 owner=root group=root
- name: 查看是否有定时更新历史
  shell: "{{ShellCmd}}"
  ignore_errors: yes
  register: result
- name: 添加cron计划任务定时执行更新
  cron: name={{CronName}} minute="00" hour="12" weekday="3" job="{{GeoBin}}"
