- name: 查看内核参数是否调整过
  shell: "{{CountSysctl}}"
  ignore_errors: yes
  register: result
- name: 修改sysctl.conf
  template: src=sysctl.conf.j2 dest={{SysctlFile}} owner=root group=root mode=0644 backup=yes
  when: result|failed
  notify:
  - sysctl come to infect
