---
# vars file for Nginx14
Nginx:
  name: nginx
  version: 1.4.0
  user:
    name: www
    home: /www
    shell: /sbin/nologin
  prefix: /usr/local/nginx
  pid: /var/run/nginx.pid
  lock: /var/lock/subsys/nginx
  environ:
    LUAJIT_LIB: /usr/local/luajit/lib
    LUAJIT_INC: /usr/local/luajit/include/luajit-2.0

DepPkgs: 
- zlib-devel
- openssl-devel
- mod_ssl
- patch
Downloads: /opt/software

ModuleLib: /usr/local/lib
ModuleLocal: /etc/ld.so.conf.d/local.conf
ModuleLuaLib: /usr/local/luajit/lib
ModuleLuaLocal: /etc/ld.so.conf.d/usr_local_luajit_lib.conf

Modules:
  libmaxminddb:
    name: libmaxminddb
    version: 1.2.0
  pcre:
    name: pcre
    version: "8.20"  
  Lua:
    name: LuaJIT
    prefix: /usr/local/luajit
    version: 2.0.2
  lua:
    name: lua-nginx-module
    version: 0.9.12
  check:
    name: nginx_upstream_check_module
    version: master
    patch_name: check_1.2.6+.patch
  hash:
    name: nginx_upstream_hash
    version: master
  purge:
    name: ngx_cache_purge
    version: "2.1"
  devel:
    name: ngx_devel_kit
    version: 0.2.18
  geoip:
    name: ngx_http_geoip2_module
    version: master
