- name: 创建远程下载目录
  file: path={{Downloads}} state=directory mode=0755
- name: 拷贝源码目录到远程主机
  synchronize: src={{WorkDir}} dest={{Downloads}} recursive=yes delete=yes
- name: 配置zabbix_agent
  shell: chdir={{Downloads}}/{{WorkDir}} ./configure --prefix={{DeployDir}} --enable-agent
- name: 编译安装
  shell: chdir={{Downloads}}/{{WorkDir}} make && make install
- name: 添加zabbix组
  group: name={{Prog}} gid={{GID}} state=present
- name: 添加zabbix用户
  user: name={{Prog}} uid={{UID}} group={{Prog}} shell={{Shell}} createhome=no
- name: 拷贝zabbix_agentd启动脚本
  template: src={{ProcName}}.j2 dest=/etc/init.d/{{ProcName}} owner=root group=root mode=0755
- name: 同步zabbix_agentd.conf配置文件
  template: src={{ProcName}}.conf.j2 dest={{DeployDir}}/etc/{{ProcName}}.conf
- name: 启动服务并设置开机启动
  service: name={{ProcName}} state=started enabled=yes
